server:
  port: 8700
spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          # 这里填写的是本地仓库地址，远程仓库直接填写远程仓库地址 http://git...
          uri: https://github.com/zhangzhixi0305/SpringCloudStudy/tree/master/config-server
          # 默认分支设定为你自己本地或是远程分支的名称
          default-label: master
eureka:
  client:
    service-url:
      defaultZone: http://eureka01:8801/eureka, http://eureka02:8802/eureka